In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("employee_promotion.csv")
df

employee_id         department     region         education gender  \
0            65438  Sales & Marketing   region_7  Master's & above      f   
1            65141         Operations  region_22        Bachelor's      m   
2             7513  Sales & Marketing  region_19        Bachelor's      m   
3             2542  Sales & Marketing  region_23        Bachelor's      m   
4            48945         Technology  region_26        Bachelor's      m   
...            ...                ...        ...               ...    ...   
54803         3030         Technology  region_14        Bachelor's      m   
54804        74592         Operations  region_27  Master's & above      f   
54805        13918          Analytics   region_1        Bachelor's      m   
54806        13614  Sales & Marketing   region_9               NaN      m   
54807        51526                 HR  region_22        Bachelor's      m   

      recruitment_channel  no_of_trainings  age  previous_year_rating  \
0                sourcing                1   35                   5.0   
1                   other                1   30                   5.0   
2                sourcing                1   34                   3.0   
3                   other                2   39                   1.0   
4                   other                1   45                   3.0   
...                   ...              ...  ...                   ...   
54803            sourcing                1   48                   3.0   
54804               other                1   37                   2.0   
54805               other                1   27                   5.0   
54806            sourcing                1   29                   1.0   
54807               other                1   27                   1.0   

       length_of_service  awards_won  avg_training_score  is_promoted  
0                      8           0                49.0            0  
1                      4           0                60.0            0  
2                      7           0                50.0            0  
3                     10           0                50.0            0  
4                      2           0                73.0            0  
...                  ...         ...                 ...          ...  
54803                 17           0                78.0            0  
54804                  6           0                56.0            0  
54805                  3           0                79.0            0  
54806                  2           0                 NaN            0  
54807                  5           0                49.0            0  

[54808 rows x 13 columns]

In [3]:
df.columns

Index(['employee_id', 'department', 'region', 'education', 'gender',
       'recruitment_channel', 'no_of_trainings', 'age', 'previous_year_rating',
       'length_of_service', 'awards_won', 'avg_training_score', 'is_promoted'],
      dtype='object')

In [4]:
df.corr()

employee_id  no_of_trainings       age  \
employee_id              1.000000        -0.005121  0.000437   
no_of_trainings         -0.005121         1.000000 -0.081278   
age                      0.000437        -0.081278  1.000000   
previous_year_rating     0.004533        -0.063126  0.006008   
length_of_service        0.001274        -0.057275  0.657111   
awards_won               0.008420        -0.007628 -0.008169   
avg_training_score      -0.000661         0.044430 -0.049500   
is_promoted              0.001206        -0.024896 -0.017166   

                      previous_year_rating  length_of_service  awards_won  \
employee_id                       0.004533           0.001274    0.008420   
no_of_trainings                  -0.063126          -0.057275   -0.007628   
age                               0.006008           0.657111   -0.008169   
previous_year_rating              1.000000           0.000253    0.027738   
length_of_service                 0.000253           1.000000   -0.039927   
awards_won                        0.027738          -0.039927    1.000000   
avg_training_score                0.075474          -0.039381    0.073963   
is_promoted                       0.159320          -0.010670    0.195871   

                      avg_training_score  is_promoted  
employee_id                    -0.000661     0.001206  
no_of_trainings                 0.044430    -0.024896  
age                            -0.049500    -0.017166  
previous_year_rating            0.075474     0.159320  
length_of_service              -0.039381    -0.010670  
awards_won                      0.073963     0.195871  
avg_training_score              1.000000     0.184386  
is_promoted                     0.184386     1.000000

In [5]:
df["education"].value_counts()

Bachelor's          36669
Master's & above    14925
Below Secondary       805
Name: education, dtype: int64

In [6]:
df["education"]=df["education"].map({"Bachelor's":0,"Master's & above":1,"Below Secondary":2})

In [7]:
df["previous_year_rating"].value_counts()

3.0    18618
5.0    11741
4.0     9877
1.0     6223
2.0     4225
Name: previous_year_rating, dtype: int64

In [8]:
df["avg_training_score"].value_counts()

50.0    2716
49.0    2681
48.0    2437
51.0    2347
60.0    2155
59.0    2064
58.0    1898
52.0    1856
47.0    1746
62.0    1450
82.0    1447
57.0    1437
81.0    1357
53.0    1324
80.0    1206
83.0    1198
84.0    1168
79.0    1160
46.0    1136
85.0    1072
56.0    1070
70.0    1055
63.0    1021
69.0    1018
54.0     997
68.0     935
78.0     933
86.0     912
71.0     898
55.0     872
67.0     728
72.0     725
64.0     708
77.0     697
87.0     655
65.0     599
66.0     580
73.0     523
76.0     516
88.0     444
74.0     433
75.0     403
44.0     335
89.0     301
90.0     185
43.0     176
91.0     117
92.0      99
93.0      84
94.0      65
42.0      62
97.0      49
96.0      48
95.0      45
98.0      37
99.0      35
41.0      26
40.0       5
39.0       2
Name: avg_training_score, dtype: int64

In [9]:
df["education"].fillna(0,inplace=True)

In [10]:
df["previous_year_rating"].fillna(df["previous_year_rating"].mean(),inplace=True)

In [11]:
df["avg_training_score"].fillna(df["avg_training_score"].mean(),inplace=True)

In [12]:
df.isna().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
awards_won              0
avg_training_score      0
is_promoted             0
dtype: int64

In [13]:
df["is_promoted"].value_counts()

0    50140
1     4668
Name: is_promoted, dtype: int64

In [14]:
df1=df.copy()
df1

employee_id         department     region  education gender  \
0            65438  Sales & Marketing   region_7        1.0      f   
1            65141         Operations  region_22        0.0      m   
2             7513  Sales & Marketing  region_19        0.0      m   
3             2542  Sales & Marketing  region_23        0.0      m   
4            48945         Technology  region_26        0.0      m   
...            ...                ...        ...        ...    ...   
54803         3030         Technology  region_14        0.0      m   
54804        74592         Operations  region_27        1.0      f   
54805        13918          Analytics   region_1        0.0      m   
54806        13614  Sales & Marketing   region_9        0.0      m   
54807        51526                 HR  region_22        0.0      m   

      recruitment_channel  no_of_trainings  age  previous_year_rating  \
0                sourcing                1   35                   5.0   
1                   other                1   30                   5.0   
2                sourcing                1   34                   3.0   
3                   other                2   39                   1.0   
4                   other                1   45                   3.0   
...                   ...              ...  ...                   ...   
54803            sourcing                1   48                   3.0   
54804               other                1   37                   2.0   
54805               other                1   27                   5.0   
54806            sourcing                1   29                   1.0   
54807               other                1   27                   1.0   

       length_of_service  awards_won  avg_training_score  is_promoted  
0                      8           0           49.000000            0  
1                      4           0           60.000000            0  
2                      7           0           50.000000            0  
3                     10           0           50.000000            0  
4                      2           0           73.000000            0  
...                  ...         ...                 ...          ...  
54803                 17           0           78.000000            0  
54804                  6           0           56.000000            0  
54805                  3           0           79.000000            0  
54806                  2           0           63.712238            0  
54807                  5           0           49.000000            0  

[54808 rows x 13 columns]

In [15]:
a=df1[df1["is_promoted"]==0]
b=df1[df1["is_promoted"]==1]
l=a.sample(n=50000)
s=b.sample(n=50000,replace=True)
df=pd.concat([s,l],axis=0)
df["is_promoted"].value_counts()

0    50000
1    50000
Name: is_promoted, dtype: int64

In [16]:
df.shape

(100000, 13)

In [17]:
columns=["employee_id","region","gender","recruitment_channel"]
df.drop(columns,axis=1,inplace=True)
df

department  education  no_of_trainings  age  \
49186         Technology        0.0                1   26   
18146  Sales & Marketing        1.0                1   40   
8887   Sales & Marketing        0.0                2   30   
28275        Procurement        1.0                1   33   
19970          Analytics        0.0                1   29   
...                  ...        ...              ...  ...   
40136  Sales & Marketing        0.0                3   29   
11402         Technology        1.0                1   42   
20297            Finance        0.0                1   30   
40607         Technology        1.0                1   43   
10033  Sales & Marketing        1.0                1   38   

       previous_year_rating  length_of_service  awards_won  \
49186              3.000000                  3           0   
18146              5.000000                  2           1   
8887               3.000000                  5           0   
28275              5.000000                  2           1   
19970              5.000000                  5           0   
...                     ...                ...         ...   
40136              3.329256                  1           0   
11402              2.000000                  7           0   
20297              4.000000                  5           0   
40607              3.000000                  6           0   
10033              3.000000                  7           0   

       avg_training_score  is_promoted  
49186                73.0            1  
18146                90.0            1  
8887                 51.0            1  
28275                91.0            1  
19970                90.0            1  
...                   ...          ...  
40136                49.0            0  
11402                81.0            0  
20297                63.0            0  
40607                81.0            0  
10033                52.0            0  

[100000 rows x 9 columns]

In [18]:
df.corr()

education  no_of_trainings       age  \
education              1.000000        -0.030316  0.269504   
no_of_trainings       -0.030316         1.000000 -0.074315   
age                    0.269504        -0.074315  1.000000   
previous_year_rating   0.028961        -0.053580  0.020259   
length_of_service      0.180758        -0.047193  0.655847   
awards_won             0.002627        -0.024195 -0.002915   
avg_training_score     0.040977         0.042107 -0.054833   
is_promoted            0.047166        -0.050979 -0.031518   

                      previous_year_rating  length_of_service  awards_won  \
education                         0.028961           0.180758    0.002627   
no_of_trainings                  -0.053580          -0.047193   -0.024195   
age                               0.020259           0.655847   -0.002915   
previous_year_rating              1.000000           0.012173    0.061058   
length_of_service                 0.012173           1.000000   -0.061685   
awards_won                        0.061058          -0.061685    1.000000   
avg_training_score                0.117780          -0.039132    0.179009   
is_promoted                       0.283377          -0.018988    0.212093   

                      avg_training_score  is_promoted  
education                       0.040977     0.047166  
no_of_trainings                 0.042107    -0.050979  
age                            -0.054833    -0.031518  
previous_year_rating            0.117780     0.283377  
length_of_service              -0.039132    -0.018988  
awards_won                      0.179009     0.212093  
avg_training_score              1.000000     0.295188  
is_promoted                     0.295188     1.000000

In [19]:
from sklearn.model_selection import train_test_split
cols=["avg_training_score","awards_won","previous_year_rating","no_of_trainings","education"]
X=df[cols]
Y=df["is_promoted"]
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(70000, 5)
(70000,)
(30000, 5)
(30000,)


### Decision Tree 

In [20]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
d=pd.DataFrame(Y_pred)
d.value_counts()

0    16047
1    13953
dtype: int64

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score
print("Accuracy : ",accuracy_score(Y_test,Y_pred))
print("Confusion Matrix : \n",confusion_matrix(Y_test,Y_pred))

Accuracy :  0.7072666666666667
Confusion Matrix : 
 [[11076  3811]
 [ 4971 10142]]


### Naive Bayes Classifier 

In [22]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
n=pd.DataFrame(Y_pred)
n.value_counts()

0    23436
1     6564
dtype: int64

In [23]:
print("Accuracy : ",accuracy_score(Y_test,Y_pred))
print("Confusion Matrix : \n",confusion_matrix(Y_test,Y_pred))

Accuracy :  0.6304333333333333
Confusion Matrix : 
 [[13618  1269]
 [ 9818  5295]]


### MultiLayer Perceptron

In [24]:
from sklearn.neural_network import MLPClassifier
model=MLPClassifier(hidden_layer_sizes=(3,3),random_state=1,learning_rate_init=0.01)
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
m=pd.DataFrame(Y_pred)
m.value_counts()

1    19677
0    10323
dtype: int64

In [25]:
print("Accuracy : ",accuracy_score(Y_test,Y_pred))
print("Confusion Matrix : \n",confusion_matrix(Y_test,Y_pred))

Accuracy :  0.6432666666666667
Confusion Matrix : 
 [[ 7254  7633]
 [ 3069 12044]]


## Boosting

### Adaboost 

In [26]:
from sklearn.ensemble import AdaBoostClassifier
model=AdaBoostClassifier()
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
b=pd.DataFrame(Y_pred)
b.value_counts()

0    16105
1    13895
dtype: int64

In [27]:
print("Accuracy : ",accuracy_score(Y_test,Y_pred))
print("Confusion Matrix : \n",confusion_matrix(Y_test,Y_pred))

Accuracy :  0.6735333333333333
Confusion Matrix : 
 [[10599  4288]
 [ 5506  9607]]


#### Adaboost with Decision tree as base classifier

In [28]:
dtc=DecisionTreeClassifier()
adb_model2=AdaBoostClassifier(n_estimators=100,base_estimator=dtc,learning_rate=0.01)
adb_model2.fit(X_train,Y_train)
dtc_pred=adb_model2.predict(X_test)
abd=pd.DataFrame(dtc_pred)
abd.value_counts()

0    16061
1    13939
dtype: int64

In [29]:
print("Accuracy : ",accuracy_score(Y_test,dtc_pred))
print("Confusion Matrix : \n",confusion_matrix(Y_test,dtc_pred))

Accuracy :  0.7077333333333333
Confusion Matrix : 
 [[11090  3797]
 [ 4971 10142]]


#### Adaboost with Naive Bayes classifier base classifier

In [30]:
nb_model=GaussianNB()
adb_model3=AdaBoostClassifier(n_estimators=100,base_estimator=nb_model,learning_rate=0.01)
adb_model3.fit(X_train,Y_train)
nb_pred=adb_model3.predict(X_test)
nbd=pd.DataFrame(nb_pred)
nbd.value_counts()

0    16128
1    13872
dtype: int64

In [31]:
print("\nAccuracy : ", accuracy_score(Y_test,nb_pred))
print("Confusion Matrix : \n", confusion_matrix(Y_test,nb_pred))


Accuracy :  0.6631
Confusion Matrix : 
 [[10454  4433]
 [ 5674  9439]]


### Bagging Technique(Random Forest) 

In [32]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
rf=pd.DataFrame(Y_pred)
rf.value_counts()

0    15929
1    14071
dtype: int64

In [33]:
print("Accuracy : ",accuracy_score(Y_test,Y_pred))
print("Confusion Matrix : \n",confusion_matrix(Y_test,Y_pred))

Accuracy :  0.7076666666666667
Confusion Matrix : 
 [[11023  3864]
 [ 4906 10207]]


In [34]:
!pip install imblearn
!pip install SMOTE

#### SMOTE 

In [35]:
from imblearn.over_sampling import SMOTE
smt=SMOTE()
X_train_new,Y_train_new=smt.fit_resample(X_train,Y_train)

In [36]:
model=DecisionTreeClassifier()
model.fit(X_train_new,Y_train_new)
Y_pred=model.predict(X_test)
d=pd.DataFrame(Y_pred)
d.value_counts()

0    15997
1    14003
dtype: int64

In [37]:
print("Accuracy : ",accuracy_score(Y_test,Y_pred))
print("Confusion Matrix : \n",confusion_matrix(Y_test,Y_pred))

Accuracy :  0.7072
Confusion Matrix : 
 [[11050  3837]
 [ 4947 10166]]


In [38]:

model=GaussianNB()
model.fit(X_train_new,Y_train_new)
Y_pred=model.predict(X_test)
n=pd.DataFrame(Y_pred)
n.value_counts()

0    23400
1     6600
dtype: int64

In [39]:
print("Accuracy : ",accuracy_score(Y_test,Y_pred))
print("Confusion Matrix : \n",confusion_matrix(Y_test,Y_pred))

Accuracy :  0.6305666666666667
Confusion Matrix : 
 [[13602  1285]
 [ 9798  5315]]


In [40]:

model=MLPClassifier(hidden_layer_sizes=(3,3),random_state=1,learning_rate_init=0.01)
model.fit(X_train_new,Y_train_new)
Y_pred=model.predict(X_test)
m=pd.DataFrame(Y_pred)
m.value_counts()

0    17848
1    12152
dtype: int64

In [41]:
print("Accuracy : ",accuracy_score(Y_test,Y_pred))
print("Confusion Matrix : \n",confusion_matrix(Y_test,Y_pred))

Accuracy :  0.6725666666666666
Confusion Matrix : 
 [[11456  3431]
 [ 6392  8721]]


In [42]:
model=AdaBoostClassifier()
model.fit(X_train_new,Y_train_new)
Y_pred=model.predict(X_test)
b=pd.DataFrame(Y_pred)
b.value_counts()

0    16105
1    13895
dtype: int64

In [43]:
print("Accuracy : ",accuracy_score(Y_test,Y_pred))
print("Confusion Matrix : \n",confusion_matrix(Y_test,Y_pred))

Accuracy :  0.6735333333333333
Confusion Matrix : 
 [[10599  4288]
 [ 5506  9607]]


In [44]:
dtc=DecisionTreeClassifier()
adb_model2=AdaBoostClassifier(n_estimators=100,base_estimator=dtc,learning_rate=0.01)
adb_model2.fit(X_train_new,Y_train_new)
dtc_pred=adb_model2.predict(X_test)
abd=pd.DataFrame(dtc_pred)
abd.value_counts()

0    16005
1    13995
dtype: int64

In [45]:
print("Accuracy : ",accuracy_score(Y_test,dtc_pred))
print("Confusion Matrix : \n",confusion_matrix(Y_test,dtc_pred))

Accuracy :  0.7074666666666667
Confusion Matrix : 
 [[11058  3829]
 [ 4947 10166]]


In [46]:
nb_model=GaussianNB()
adb_model3=AdaBoostClassifier(n_estimators=100,base_estimator=nb_model,learning_rate=0.01)
adb_model3.fit(X_train_new,Y_train_new)
nb_pred=adb_model3.predict(X_test)
nbd=pd.DataFrame(nb_pred)
nbd.value_counts()

0    16065
1    13935
dtype: int64

In [47]:
print("\nAccuracy : ", accuracy_score(Y_test,nb_pred))
print("Confusion Matrix : \n", confusion_matrix(Y_test,nb_pred))


Accuracy :  0.6634
Confusion Matrix : 
 [[10427  4460]
 [ 5638  9475]]


In [48]:
model=RandomForestClassifier()
model.fit(X_train_new,Y_train_new)
Y_pred=model.predict(X_test)
rf=pd.DataFrame(Y_pred)
rf.value_counts()

0    15910
1    14090
dtype: int64

In [49]:
print("Accuracy : ",accuracy_score(Y_test,Y_pred))
print("Confusion Matrix : \n",confusion_matrix(Y_test,Y_pred))

Accuracy :  0.7069666666666666
Confusion Matrix : 
 [[11003  3884]
 [ 4907 10206]]


In [51]:
from imblearn.under_sampling import RandomUnderSampler
model=DecisionTreeClassifier()
over = SMOTE(sampling_strategy=0.1)
under = RandomUnderSampler(sampling_strategy=0.5)
steps = [('o', over), ('u', under), ('m', model)]